@host = http://localhost:3001

//commit test

//USERS

###
POST {{host}}/api/auth/login2
Content-Type: application/json

{
    "email": "carlo@gmail.com",
    "password" : "1234"
}

###
GET {{host}}/api/auth/logout

### GET ALL USERS
GET {{host}}/api/users
x-auth: 23423

### GET USER BY _ID
GET {{host}}/api/users/6620682a8c79b23fa54bd305
x-auth: 23423

### GET BY COOKIES
GET {{host}}/api/users/search/me

### GET USER BY USERNAME
GET {{host}}/api/users/username/Guillermo
x-auth: 23423

### GET USER BY USERNAME
GET {{host}}/api/users/username/Carlo
x-auth: 23423

### POST NEW USER
POST {{host}}/api/users
Content-Type: application/json

{
    "username": "IMTHEBIGGESTLOL",
    "userPhoto": "",
    "name": "Daniel Arellano",
    "bio": "Naci en GDL y me encanta cocinar",
    "email": "dany@gmail.com",
    "password": "1234",
    "phone": "3345621789",
    "birthday": "2004-04-04T06:00:00.000Z",
    "country": "Mexico"
}

### POST NEW USER
POST {{host}}/api/users
Content-Type: application/json

{
    "username": "Carlo",
    "userPhoto": "",
    "name": "Carlo Santoro",
    "bio": "x",
    "email": "carlo@gmail.com",
    "password": "1234",
    "phone": "3345621789",
    "birthday": "2004-04-04T06:00:00.000Z",
    "country": "Mexico"
}

### PUT USER (UPDATE)
PUT {{host}}/api/users/username/Guillermo
Content-Type: application/json

{
    "username": "Guillermo",
    "userPhoto": "",
    "name": "El Guille Edit",
    "bio": "soy estudiante",
    "email": "guille@gmail.com",
    "password": "4321",
    "phone": "3345621789",
    "birthday": "2004-06-23T06:00:00.000Z",
    "country": "Mexico"
}

### DELETE USER
DELETE {{host}}/api/users/username/Carlo

### GET CURRENT USER RECIPES
GET {{host}}/api/recipes/mine

### GET CURRENT USER FAVORITES
GET {{host}}/api/recipes/favorites

### POST RECIPE TO FAVORITES
POST {{host}}/api/recipes/favorites/662962c76c7b8ce78f29353a

### DELETE RECIPE IN FAVORITES
DELETE {{host}}/api/recipes/favorites/662962c76c7b8ce78f29353a




### ADD A NEW REVIEW SUBSCRIPTION TO USER
POST {{host}}/api/users/6620682a8c79b23fa54bd305/reviews/subscribe

### DELETE A REVIEW SUBSCRIPTION
DELETE {{host}}/api/users/6620682a8c79b23fa54bd305/reviews/subscribe

### 
# POST {{host}}/api/auth/login
# Content-Type: application/json

# {
#     "email": "dany@gmail.com",
#     "password" : "1234"
# }

###

POST {{host}}/api/auth/login2
Content-Type: application/json

{
    "email": "guille@gmail.com",
    "password" : "4321"
}

//RECIPES

###
GET {{host}}/api/recipes

### GET ALL RECIPES ADMIN
GET {{host}}/api/recipes/search?steps=2&&cook_time_gte=15
x-auth: 23423

### GET ALL RECIPES NOT ADMIN
GET {{host}}/api/recipes
x-auth: 2342

###
GET {{host}}/api/recipes/66256e68c3d0c110c660a8f8
x-auth: 23423

//Fecha, rating
### POST NEW RECIPE
POST {{host}}/api/recipes
Content-Type: application/json

{
    "title": "Tacos",
    "description": "Soooo delocious",
    "ingredients": [
        "Tortilla",
        "Meat"
    ],
    "steps": [
        "Cook the meat",
        "Eat it"
    ],
    "photo": "https://i.pinimg.com/564x/5f/57/da/5f57da87bc9041c42ab120e2857da837.jpg",
    "cook_time": 10,
    "prep_time": 5
}

###PUT RECIPE (UPDATE)
PUT {{host}}/api/recipes/66256e68c3d0c110c660a8f8
Content-Type: application/json

{
    "title": "Mushroom Pizza EDIT",
    "description": "Very italian",
    "ingredients": [
        "Mushroom",
        "Cheese"
    ],
    "steps": [
        "Bake it",
        "Eat it"
    ],
    "photo": "https://i.pinimg.com/564x/11/e0/37/11e037e9c94e2da47e2abbee299f023f.jpg",
    "cook_time": 25,
    "prep_time": 15
}

###DELETE RECIPE
DELETE {{host}}/api/recipes/66316976d1ea5cac7623908a

###POST MESSAGE TO A RECIPE (CHAT)
POST {{host}}/api/recipes/662c5ca131d708cc0b160897/chat
Content-Type: application/json

{
    "content": "Deliciosa pizza la vrd"
}

### GET CHAT DE UNA RECETA EN ESPECIFICO
GET {{host}}/api/recipes/chat/66256e68c3d0c110c660a8f8

//PRUEBA DE QUE ESTA PARTE DEL CODIGO DE ACTUALICE EN GITHUB :)!!!!!


//Reviews

### POST REVIEW
POST {{host}}/api/reviews/66295c636264b2ab44818399
Content-Type: application/json

{
    "comment": "Great recipe, the nachos were delicious",
    "rating": 4.2
}

### DELETE REVIEW
DELETE {{host}}/api/reviews/66295c636264b2ab44818399/662c561141abc223196c6f24

###
GET {{host}}/api/categories
x-auth: 23423

###
POST {{host}}/api/categories
Content-Type: application/json

{
    "name": "Pastas",
    "photo": "https://i.pinimg.com/564x/b9/5e/28/b95e28ff906b6fdd024d5799e98f2573.jpg"
}