@host = http://localhost:3000

//USERS

### GET ALL USERS
GET {{host}}/api/users
x-auth: 23423

### GET USER BY _ID
GET {{host}}/api/users/6620682a8c79b23fa54bd305
x-auth: 23423

### GET USER BY USERNAME
GET {{host}}/api/users/email/Guillermo
x-auth: 23423

### POST NEW USER
POST {{host}}/api/users
Content-Type: application/json

{
    "username": "IMTHEBIGGESTLOL",
    "userPhoto": "",
    "name": "Daniel Arellano",
    "bio": "Naci en GDL y me encanta cocinar",
    "email": "dany@gmail.com",
    "password": "1234",
    "phone": "3345621789",
    "birthday": "2004-04-04T06:00:00.000Z",
    "country": "Mexico"
}

### PUT USER (UPDATE)
PUT {{host}}/api/users/username/Guillermo
Content-Type: application/json

{
    "username": "Guillermo",
    "userPhoto": "",
    "name": "El Guille",
    "bio": "soy estudiante",
    "email": "guille@gmail.com",
    "password": "4321",
    "phone": "3345621789",
    "birthday": "2004-06-23T06:00:00.000Z",
    "country": "Mexico"
}

### DELETE USER
DELETE {{host}}/api/users/email/juanito@gmail.com
x-auth: 23423

### ADD A NEW REVIEW SUBSCRIPTION TO USER
POST {{host}}/api/users/6620682a8c79b23fa54bd305/reviews/subscribe
x-token: Ivan

### DELETE A REVIEW SUBSCRIPTION
DELETE {{host}}/api/users/6620682a8c79b23fa54bd305/reviews/subscribe
x-token: Ivan

### 
POST {{host}}/api/login
Content-Type: application/json

{
    "email": "guille@gmail.com",
    "password" : "4321"
}


//RECIPES

### GET ALL RECIPES ADMIN
GET {{host}}/api/recipes
x-auth: 23423

### GET ALL RECIPES NOT ADMIN
GET {{host}}/api/recipes
x-auth: 2342

###
GET {{host}}/api/recipes/66256e68c3d0c110c660a8f8
x-auth: 23423

//Fecha, rating
### POST NEW RECIPE
POST {{host}}/api/recipes
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkZyb250VXNlciIsIl9pZCI6IjY2MjljODNiODI1NmU2MzFhZGFlOWZlMSIsImlhdCI6MTcxNDAxNzE4NiwiZXhwIjoxNzE0MDIwNzg2fQ.XSyGrbLiXoTZY546rM3bu15mGdoOrwO0t80tWkHLOcc
Content-Type: application/json

{
    "title": "Egg Omellette",
    "description": "Very delicius",
    "ingredients": [
        "Eggs",
        "Slat"
    ],
    "steps": [
        "cocinar",
        "comer"
    ],
    "uid": "14",
    "photo": "https://i.pinimg.com/736x/45/51/74/455174d200410eae4e74cdb7eb97013b.jpg",
    "cook_time": 10,
    "prep_time": 5
}

###PUT RECIPE (UPDATE)
PUT {{host}}/api/recipes/66256e68c3d0c110c660a8f8
x-token: Guillermo
Content-Type: application/json

{
    "title": "Kimchi de Cerdo EDIT",
    "description": "Es una delicia en plato EDIT",
    "ingredients": [
        "carne",
        "soya",
        "huevo"
    ],
    "steps": [
        "cocinar",
        "comer"
    ],
    "reviews": [
        "muy deliciosa"
    ],
    "categories": [],
    "uid": "5",
    "rating": 4.3,
    "photo": "https://static.vecteezy.com/system/resources/previews/002/873/829/large_2x/stir-fried-pork-with-kimchi-korean-food-style-free-photo.jpg",
    "cook_time": 20,
    "prep_time": 15
}

###DELETE RECIPE
DELETE {{host}}/api/recipes/662056c78c79b23fa54bd303
x-token: Guillermo
x-auth: 23423

###POST MESSAGE TO A RECIPE (CHAT)
POST {{host}}/api/recipes/66256e68c3d0c110c660a8f8/chat
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikd1aWxsZXJtbyIsIl9pZCI6IjY2MjJiZTlkNTdlMzFmYmQ2MzI1NDZjNiIsImlhdCI6MTcxMzkyMzY2OSwiZXhwIjoxNzEzOTI3MjY5fQ.U2q8cz4xisPlJDU-rVxChu7iVbju1CmmEDzxtV_DCLI
Content-Type: application/json

{
    "content": "Sigo y sigo comiendo"
}

### POST RECIPE TO FAVORITES
POST {{host}}/api/recipes/favorites/66256e68c3d0c110c660a8f8
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikd1aWxsZXJtbyIsIl9pZCI6IjY2MjJiZTlkNTdlMzFmYmQ2MzI1NDZjNiIsImlhdCI6MTcxNDAwNzUyNSwiZXhwIjoxNzE0MDExMTI1fQ.vC-GWDLqmRKW0rCQjP7fRGGXzb7Wyvm7-cCSnD5rIls

### DELETE RECIPE IN FAVORITES
DELETE {{host}}/api/recipes/favorites/66256e68c3d0c110c660a8f8
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikd1aWxsZXJtbyIsIl9pZCI6IjY2MjJiZTlkNTdlMzFmYmQ2MzI1NDZjNiIsImlhdCI6MTcxNDAwNzUyNSwiZXhwIjoxNzE0MDExMTI1fQ.vC-GWDLqmRKW0rCQjP7fRGGXzb7Wyvm7-cCSnD5rIls

### GET CURRENT USER RECIPES
GET {{host}}/api/recipes/mine
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikd1aWxsZXJtbyIsIl9pZCI6IjY2MjJiZTlkNTdlMzFmYmQ2MzI1NDZjNiIsImlhdCI6MTcxNDAwNzUyNSwiZXhwIjoxNzE0MDExMTI1fQ.vC-GWDLqmRKW0rCQjP7fRGGXzb7Wyvm7-cCSnD5rIls

### GET CURRENT USER FAVORITES
GET {{host}}/api/recipes/favorites
x-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikd1aWxsZXJtbyIsIl9pZCI6IjY2MjJiZTlkNTdlMzFmYmQ2MzI1NDZjNiIsImlhdCI6MTcxNDAwNzUyNSwiZXhwIjoxNzE0MDExMTI1fQ.vC-GWDLqmRKW0rCQjP7fRGGXzb7Wyvm7-cCSnD5rIls

### GET CHAT DE UNA RECETA EN ESPECIFICO
GET {{host}}/api/recipes/chat/66256e68c3d0c110c660a8f8

//PRUEBA DE QUE ESTA PARTE DEL CODIGO DE ACTUALICE EN GITHUB :)!!!!!


//MESSAGES



###
GET {{host}}/api/categories
x-auth: 23423

###
GET {{host}}/users/4/test@abc.com

###
GET {{host}}/users?minID=4&maxID=6

###
GET {{host}}/users?pageNumber=2&pageSize=5

###
POST {{host}}/users
Content-Type: application/json

{
    "name":"Test Name",
    "email": "T2est email",
    "age":24
}

###
PUT {{host}}/users/4
Content-Type: application/json

{
    "name": "Put Name"
}

###
DELETE {{host}}/users/4
x-auth: 23423

